name: networkintrusion
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scikit-learn
  - joblib
  - matplotlib
  - seaborn
  - pytorch
  - pip:
    - gymnasium
    - stable-baselines3
    - tensorboard
    - optuna
    - kaggle
    -kagglehub